-- Dimension Tables (13)
select * from SF_AGENTS_DB.AGENTS_STORAGE.ACCOUNT_DIM;
select * from SF_AGENTS_DB.AGENTS_STORAGE.CAMPAIGN_DIM;
select * from SF_AGENTS_DB.AGENTS_STORAGE.CHANNEL_DIM;
select * from SF_AGENTS_DB.AGENTS_STORAGE.CUSTOMER_DIM;
select * from SF_AGENTS_DB.AGENTS_STORAGE.DEPARTMENT_DIM;
select * from SF_AGENTS_DB.AGENTS_STORAGE.EMPLOYEE_DIM;
select * from SF_AGENTS_DB.AGENTS_STORAGE.JOB_DIM;
select * from SF_AGENTS_DB.AGENTS_STORAGE.LOCATION_DIM;
select * from SF_AGENTS_DB.AGENTS_STORAGE.PRODUCT_CATEGORY_DIM;
select * from SF_AGENTS_DB.AGENTS_STORAGE.PRODUCT_DIM;
select * from SF_AGENTS_DB.AGENTS_STORAGE.REGION_DIM;
select * from SF_AGENTS_DB.AGENTS_STORAGE.SALES_REP_DIM;
select * from SF_AGENTS_DB.AGENTS_STORAGE.VENDOR_DIM;

-- Fact Tables (4)
select * from SF_AGENTS_DB.AGENTS_STORAGE.HR_EMPLOYEE_FACT;
select * from SF_AGENTS_DB.AGENTS_STORAGE.MARKETING_CAMPAIGN_FACT;
select * from SF_AGENTS_DB.AGENTS_STORAGE.SALES_FACT;

-- Salesforce CRM Tables (3)

select * from SF_AGENTS_DB.AGENTS_STORAGE.SF_ACCOUNTS;
select * from SF_AGENTS_DB.AGENTS_STORAGE.SF_CONTACTS;
select * from SF_AGENTS_DB.AGENTS_STORAGE.SF_OPPORTUNITIES;

